@rootUrl=http://localhost:7071
@fileName=contract_001_Fourth_Coffee_20250310.pdf

POST {{rootUrl}}/api/process
Content-Type: application/json

{
    "values": [
        {
            "recordId": "1",
            "data": {
              "metadata_storage_name": "{{fileName}}"
            }
        }
    ]
    
}